import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'
import Footer from './components/Footer'
import SocialMedia from './components/SocialMedia'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />
        <Sidebar />
        {children}
        <Footer />
        <SocialMedia />
      </body>
    </html>
  )
}
