import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  )
}
